#
# Makefile for misc devices that really don't fit anywhere else.
#
#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2022 KYOCERA Corporation
#
obj-y += kc_st7701si_fwvga_dsi_vdo_5a.o


ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

