#
# Makefile for misc devices that really don't fit anywhere else.
#
#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2022 KYOCERA Corporation
#
obj-y += kc_auo_a026qtn01_0_qvga_dsi_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

